name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'etc/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
        - "25.2"
        - "25.3"
        - "26.2"
        - "26.3"
        - "27.1"
        - snapshot
        include:
        - emacs_version: "25.2"
          allow_failure: true
        - emacs_version: snapshot
          allow_failure: true
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'
    - uses: actions/checkout@v2
    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make test'
    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'
